### ISSUE TITLE
Atomic Soldering Iron Can't Disassemble

### ISSUE THREAD

**Issue by yay855** [thelonestander/Lones-Tech-and-Weapons-mod#3]
The atomic soldering iron doesn't disassemble items- you can use it to repair things just fine, but attempting to use it to disassemble anything simply tells you that you need more charges.

**Comment by yay855** [comment]
Turns out it applies to the hotplate too. I can use it to heat up food to eat, but not to cook it.

**Comment by thelonestander** [comment]
Looking into this today.

**Comment by thelonestander** [comment]
Should be good to go, Changed it to be solar like the atomic water purifier which seems to work now. Have fun guys!
