### ISSUE TITLE
Atomic Thermal Clothing Can't Turn Off

### ISSUE THREAD

**Issue by yay855** [thelonestander/Lones-Tech-and-Weapons-mod#4]
There's a bug involving atomic thermal clothing, namely that they can't turn off; they require at least 1 charge to turn off, but, being atomic items, they have infinitely zero charge, and thus you can turn them on, but not off.

**Comment by thelonestander** [comment]
Should be fixed now. Tested in the mod. Made sure it all goes on, and off.
