### ISSUE TITLE
Multiple JSON Errors

### ISSUE THREAD

**Issue by yay855** [thelonestander/Lones-Tech-and-Weapons-mod#5]
There's several errors in the latest version. Here's the list:

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Electronic tools/electronics.json:29:21: Invalid or misplaced field name "revert_to" in JSON data

        "msg": "You activate the flashlight app.",
        "active": true,
        "revert_to":
                    ^
                     "wearable_smart_phone",
        "need_charges": 5,
        "need_charges_msg": "The smartphone's charge is too low.",

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

-----------------

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Itemgroups/collections_trades.json:8:20: Invalid or misplaced field name "distribution" in JSON data

    "//2": "often spawns a box to hold everything, sometimes a plastic sheet to cover it, and then some stuff in the box.",
    "subtype": "collection",
    "distribution":
                   ^
                    [ { "item": "imalentms18", "prob": 3 } ]
  }
]

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

-----------------

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Lones Translocator gates/gates.json:97:15: Invalid or misplaced field name "entries" in JSON data

    "id": "rare",
    "//": "Items that should have very low frequencies and or few locations.",
    "entries":
              ^
               [
      { "item": "translocator", "prob": 5 },
      { "item": "portable_translocator_gate", "prob": 10 },

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

-----------------

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Lones Translocator gates/gates.json:107:15: Invalid or misplaced field name "entries" in JSON data

    "id": "nanofab_recipes",
    "//": "Very rare high level loot. This list doesn't spawn anywhere directly, it is used to create the recipes inside nanofabricator templates. ",
    "entries":
              ^
               [ { "item": "translocator", "prob": 5 }, { "item": "portable_translocator_gate", "prob": 10 } ]
  },
  {

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

-----------------

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Lones Translocator gates/gates.json:112:15: Invalid or misplaced field name "entries" in JSON data

    "type": "item_group",
    "id": "science",
    "entries":
              ^
               [ { "item": "translocator", "prob": 1 }, { "item": "portable_translocator_gate", "prob": 2 } ]
  },
  {

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

-----------------

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Lones Translocator gates/gates.json:117:15: Invalid or misplaced field name "entries" in JSON data

    "type": "item_group",
    "id": "teleport",
    "entries":
              ^
               [ { "group": "translocator_spawn", "prob": 5 }, { "item": "portable_translocator_gate", "prob": 20 } ]
  },
  {

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

-----------------

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Melee weapons/misc.json:121:57: Invalid or misplaced field name "str_p" in JSON data

    "copy-from": "electro_chainwhip",
    "type": "TOOL",
    "name": { "str": "Electro Chain Whip (on)", "str_p":
                                                        ^
                                                         "Electro Chain Whips (on)" },
    "description": "A long slightly rusty chain usable as a whip.  This one has a series of wires and connectors to it, and a place for a battery at the hilt.  It's currently on, arcing with electricity that wi

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

-----------------

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Melee weapons/misc.json:298:50: Invalid or misplaced field name "str_p" in JSON data

    "type": "TOOL",
    "category": "weapons",
    "name": { "str": "Chain sword (on)", "str_p":
                                                 ^
                                                  "Chain swords (on)" },
    "description": "The chainsaw blades are on and are hungry!",
    "looks_like": "longsword",

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

-----------------

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Melee weapons/misc.json:494:56: Invalid or misplaced field name "str_p" in JSON data

    "type": "TOOL",
    "category": "weapons",
    "name": { "str": "Electro longsword (on)", "str_p":
                                                       ^
                                                        "Electro longsword (on)" },
    "description": "You feel the electricity hum through the blade.",
    "looks_like": "longsword",

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

-----------------

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Recipes/bashing.json:31:22: Invalid or misplaced field name "activity_level" in JSON data

    "result": "dual_knife_trench",
    "type": "recipe",
    "activity_level":
                     ^
                      "NO_EXERCISE",
    "category": "CC_WEAPON",
    "subcategory": "CSC_WEAPON_CUTTING",

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

-----------------

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Guns-Bows/Bows/crossbows.json:25:19: Invalid or misplaced field name "max_charges" in JSON data

    "range": 12,
    "dispersion": 500,
    "max_charges":
                  ^
                   10,
    "recoil": 30,
    "durability": 6,

-----------------

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Lones Translocator gates/gates.json:97:15: Invalid or misplaced field name "entries" in JSON data

    "id": "rare",
    "//": "Items that should have very low frequencies and or few locations.",
    "entries":
              ^
               [
      { "item": "translocator", "prob": 5 },
      { "item": "portable_translocator_gate", "prob": 10 },

--------------

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Lones Translocator gates/gates.json:107:15: Invalid or misplaced field name "entries" in JSON data

    "id": "nanofab_recipes",
    "//": "Very rare high level loot. This list doesn't spawn anywhere directly, it is used to create the recipes inside nanofabricator templates. ",
    "entries":
              ^
               [ { "item": "translocator", "prob": 5 }, { "item": "portable_translocator_gate", "prob": 10 } ]
  },
  {

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

---------------------

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Lones Translocator gates/gates.json:112:15: Invalid or misplaced field name "entries" in JSON data

    "type": "item_group",
    "id": "science",
    "entries":
              ^
               [ { "item": "translocator", "prob": 1 }, { "item": "portable_translocator_gate", "prob": 2 } ]
  },
  {

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

----------------------------

 DEBUG    : (json-error)
Json error: ./mods/Lones-Tech-and-Weapons-mod/Lones Translocator gates/gates.json:117:15: Invalid or misplaced field name "entries" in JSON data

    "type": "item_group",
    "id": "teleport",
    "entries":
              ^
               [ { "group": "translocator_spawn", "prob": 5 }, { "item": "portable_translocator_gate", "prob": 20 } ]
  },
  {

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

------------------

 DEBUG    : (json-error)
Json error: ./mods/Expansion_Tefnut/items/vehicle_parts/fridge_item.json:16:18: Invalid or misplaced field name "insulation" in JSON data

    "category": "veh_parts",
    "price": "400 USD",
    "insulation":
                 ^
                  4
  }
]

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 124
 VERSION  : BN 0b44cbc

---------------------

**Comment by thelonestander** [comment]
Fixed with latest updates
