### ISSUE TITLE
Can unload batteries from atomic tools

### ISSUE THREAD

**Issue by yay855** [thelonestander/Lones-Tech-and-Weapons-mod#6]
The atomic tools can be unloaded, giving you free battery charge that you can load into other batteries.

**Comment by yay855** [comment]
I also noticed that the atomic water purifier and hotplate aren't even listed for crafting, either.

**Comment by thelonestander** [comment]
> The atomic tools can be unloaded, giving you free battery charge that you can load into other batteries.

These are now fixed as well.

**Comment by thelonestander** [comment]
> I also noticed that the atomic water purifier and hotplate aren't even listed for crafting, either.

Ill be looking into these options here in a bit.

**Comment by thelonestander** [comment]
> I also noticed that the atomic water purifier and hotplate aren't even listed for crafting, either.

I am unable to do this via the hardcoded stuff in game currently. :/
