### ISSUE TITLE
Lockpick error

### ISSUE THREAD

**Issue by KoverUnderCover** [thelonestander/Lones-Tech-and-Weapons-mod#9]
Catch some lockpick error in new BN update

 DEBUG    : (json-error)
Json error: D:/Catapult/bn/userdata/mods/Lones-Tech-and-Weapons-mod-main/Tools/electronics.json:245:56: Invalid or misplaced field name "pick_quality" in JSON data

    "color": "light_gray",
    "qualities": [ [ "LOCKPICK", 12 ] ],
    "use_action": { "type": "picklock", "pick_quality":
                                                       ^
                                                        12 }
  },
  {

 FUNCTION : report_unvisited
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\json.cpp
 LINE     : 125
 VERSION  : BN 0.4

**Comment by thelonestander** [comment]
Fixed in last update
